packages:
  - apps/*
  - packages/*

allowBuilds:
  msw: false

catalog:
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  lucide-react: ^1.14.0
  react: ^19.2.5
  react-dom: ^19.2.5
  tailwindcss: ^4.2.4
